#import "/lib/lib.typ": card, placard
#import "macros.typ": IntrospectionView, OverView, PatientView, demourl, placeholder, requirement, toolname
#import "@preview/cades:0.3.1": qr-code

#show: placard.with(
  title: [#toolname: A Fully Interpretable EEG Dementia Screening Assistant],
  authors: ([Leonhard Euler#super[1]],),
  affiliations: ([Institute of Visual Computing, Graz University of Technology, Austria], [University of Padova, Italy],),
  num-columns: 1,
  paper: "a0",
  flipped: false,
  colors: (accent: rgb("#7593e6"), title: rgb("#1a1a1a"), paper-fill: rgb("#f4f7f9"), card-fill: rgb("#f4f7f9")),
  sizes: (card: 26pt, h1: 34pt, h2: 28pt, body: 32pt, authors: 23pt),
  margin: (top: 1.8cm, bottom: 2.6cm, x: 1.8cm),
  footer: (
    logo: path("/lib/assets/ivc-logo.pdf"),
    content: [
      #text(
        size: 16pt,
      )[
        *Acknowledgements:* This work is supported by the HEREDITARY Project, as part of the European Union's Horizon Europe research and innovation programme under grant agreement No GA 101137074.
        *Contact*: #link("mailto:leonhard.euler@tugraz.at").
      ]
    ],
  ),
)

*#toolname* is an interactive *dementia classification assistant*, which helps clinicians screen for dementia from EEG recordings. It is built around *xEEGNet* @2025-Zanola-xEEGNet, a small, fully *interpretable* machine learning model with only $F dot.c (C+L+2) = 168$ trainable parameters, for the classification of two dementia subtypes from raw EEG traces @2023-miltiadous-dataset.

#placeholder(height: 20cm)[Poster Headline]

#grid(columns: (1fr, 1fr, 1fr), gutter: 1.2em, ..([Method], [Evaluation], [Results]).map(title => card(title: title)[
  #lorem(40)
  #align(center, placeholder(width: 80%, height: 12cm)[Figure])
  #lorem(20)
]))

#lorem(50)
#placeholder(height: 10cm)[More Content]

#grid(
  columns: (27cm, 1fr),
  gutter: 1.2em,
  [
    #card(
      title: [Embedding Introspection View],
    )[
      #toolname also puts an emphasis on the embeddings generated by the model, as they serve a multitude of purposes.

      #placeholder(height: 16cm)[Introspection view screenshot]
      // #v(-0.8em)
      #text(
        size: 21pt,
        style: "italic",
      )[
        A per-patient PCA scatter plot of window-level activations (embeddings), linked to a heatmap table of all seven band-activation dimensions, surfacing which bands drive misclassifications.
        In the example below, the theta and alpha bands carry very high Shapley feature importance, and they alone can predict much of the outcome.
      ]
    ]
  ],
  [
    #grid(
      columns: (1fr, 8cm),
      gutter: 1.2em,
      card(
        title: [Conclusion & Outlook],
      )[
        *#toolname* is an open-source EEG dementia classification assistant that makes the complete inference pipeline of the xEEGNet dementia classifier interactively explorable - from raw EEG signals to per-band spectral features, spatial topomaps, and signed class contributions.
        By grounding every visual element in the model's *architecture-intrinsic quantities*, #toolname provides a transparency that post-hoc attribution methods cannot match.

        *Physiological Motivation*: xEEGNet's architecture is motivated by medical insights, e.g. the fixed bandpass filters are well-known features in EEG literature.
        Lower relative *$alpha$-band power*, for example, is a *known dementia indicator*.
        For better reference, we also allow the user to compare a patient's data to the cohort distribution.

        *Central Model Claim*: Architecture-intrinsic explainability beats post-hoc attribution: clinicians can inspect *real evidence*, not saliency maps.
        Interviews with an experienced neurologist confirm the pipeline matches clinical reasoning, especially for healthy-vs.-dementia screening.

        *Voice Control Integration*: The natural-language interface is an accessibility highlight, non-expert users can navigate the tool easily, even by voice interaction.
        A case for no-hands interaction in the lab could also be made.

        *Future Work* includes counterfactuals, model extensions and new model architectures, a broader usability study and additional EEG datasets.

        #v(-1em)
      ],
      [
        #v(0.6em)
        Source Code:
        #v(-0.8em)
        #qr-code("https://github.com/hereditary-eu/EEGlass", width: 100%)

        Live Demo:
        #v(-0.8em)
        #qr-code("https://hereditary.cgv.tugraz.at/all-in-on-eeg/", width: 100%)
      ],
    )

    #card(title: "References")[
      #set text(size: 18pt)
      #v(-0.5em)
      #bibliography("./sources.bib", title: none)
    ]
  ],
)

#card(
  title: "Takeaways & Outlook",
)[
  Architecture-intrinsic explainability beats post-hoc attribution: clinicians can inspect real evidence, not saliency maps.
  A neurologist confirmed the pipeline matches clinical reasoning, especially for healthy-vs.-dementia screening.
  *Future work:* broader usability study, additional cohorts, live-streamed EEG, counterfactual explanations.
]
#align(center, text(size: 20pt, style: "italic")[Open source -- try it live at #demourl])
